### ISSUE TITLE
Basically Infinite Minions

### ISSUE THREAD

**Issue by Jacklz** [Lanboost/TModLoader_LansAutoSummon#1] opened 2019-11-27 13:11 UTC
There appears to be a bug when using this mod in conjunction with the calamity mod. I have tested this with ONLY calamity and autosummon to make sure another mod wasn't the cause. If you place the item "Staff of the Mechworm" in the auto summon slot, it will keep summoning minions and will exceed the player's max minions insanely quickly. You will shortly have like 500 minions, not sure where it stops. This only seems to happen however, if you don't currently have any minions summoned. If you manually summon one minion (from the mechworm staff) and then put the staff in the autosummon slot, nothing happens (unless you have more minion slots available for your character). Its only when you don't have anything summoned. I don't know if this happens with more or other weapons but hopefully you can fix this universally.

**Comment by Lanboost** [comment] 2019-11-27 17:02
To be honest this is actually a unfix-able issue in the way that this mod works.

Some minions, for example stardust dragon and apparently mechworm have special summoning code.

Instead of summoning 1 type of projectile, it summons more usually around ~3 head, body and tail and links them together in ai code etc. 

The way that this mod works, there is no way for me to know what projectile to summon except by reading the projectile specified by the weapon (usually the head) so it will summon only heads. In this case the head apparently takes 0 minion slots, meaning you will never fill up your minion slots and it will summon until max projectiles or server crashes.

As this mod have chosen not to use the summoning code in the item (basically calling use_item) and instead directly summoning the projectiles (summons) issues like this can only be hardcode fixed.

So solutions:
- Hardcode a special solution for Calamities mechworm, similar to the hardcoded stardust dragon, which will not fix issues bound to show up on other items/mods.

- Go back to use "use_item" but modify use_time, mana_usage, selected_item etc to fake using the item. This will solve all issues. This however will take time/effort to get to work out all the kinks

So to conclude, thanks for the report but I do not have the energy to fix this issue atm. So sadly do not expect a fix anytime soon. If the issue is proven fatal for servers (people abusing it) I might add a quick fix to disable summoning of this one item

Regards
Lan

**Comment by milkev** [comment] 2021-08-27 19:28
this happens with the cold divinity too, it just spews particles out of the players body and never summons anything

configs to 'use item instead of spawn summon' or 'blacklist x items' would be nice to have, if possible

**Comment by Lanboost** [comment] 2021-09-01 20:05
This issue should now hopefully be fixed.

It is fixed by using method 2 of forcing a "ItemCheck" call on client side to use the normal spawning code. Meaning "most" if not all summoning items should work correctly. 

**Side note:**

Calamitys "cold divinity" item is not working as intended when removing the minion buff. It should remove all minions attached to it, but it does not. This is an error on their side and should be reported there. No one will notice, but basically once you summon "cold divinity" summons there is no way to replace them except dc/dying.


Feel free to open up the issue or a new one if error persist.

Regards Lan

**Closed as completed by Lanboost** 2021-09-01 20:05 UTC
