### ISSUE TITLE
game freezes if a summoning item is put into the autosummon slot (1.4 alpha if that makes a difference)

### ISSUE THREAD

**Issue by Walparr** [Lanboost/TModLoader_LansAutoSummon#3] opened 2021-09-03 11:08 UTC
when i attempt to put a summoning item into the autosummon slot (says its 9 but actually is 0) the game makes a burst summon sound and then freezes, no amount of waiting unfreezes it, ive had to close the game with task manager (if this issue report is missing information ask me since im not experienced in writing these)

**Comment by Lanboost** [comment] 2021-09-04 16:44
Please fill in the following:

**- Is this for TModLoader Beta (Terraria 1.4) or for Terraria 1.3?**

**- Multiplayer or single player?**

**- Item placed into hotkey? (0 as you say, I will update description)**

**Comment by Walparr** [comment] 2021-09-04 18:19
It is for the TModLoader Alpha 1.4 (as i stated in the title)
Singleplayer
0 indeed

**Comment by Walparr** [comment] 2021-09-04 18:24
i have also confirmed it happens with both modded and not modded summoning items

**Comment by Lanboost** [comment] 2021-09-04 23:14
I believe the issue is now resolved with version 0.3.3

Regards
Lan

**Closed as completed by Lanboost** 2021-09-04 23:14 UTC
